/*
 * SolutionsHub Help Center -- content, part 1: Getting started + Solutions Hub.
 *
 * HOW TO KEEP THIS CURRENT: every time a feature is added or changed, edit its article here (or add one),
 * set `updated` to today's date, and add a line to help-changelog.js. The "Services" section of the Help
 * Center is generated from the Hub's own catalog (PILLARS in app.js), so it updates by itself.
 *
 * Article fields: id (unique, kebab-case), title, def (what it is, 1-2 sentences), where (how to reach it),
 * link {href,label} (opens the feature; paths are relative to /help/), why (what it is used for),
 * steps [..], notes [..], added, updated (YYYY-MM-DD), kw [extra search words].
 */
(function () {
  window.HELP_SECTIONS = window.HELP_SECTIONS || [];
  var HUB = '../index.html';
  window.HELP_SECTIONS.push(
    {
      id: 'getting-started', title: 'Getting Started',
      intro: 'Signing in, finding your way around the home screen, and getting help.',
      articles: [
        { id: 'sign-in', title: 'Signing in and out',
          def: 'Every CodeBlue tool sits behind one shared Microsoft 365 sign-in. Sign in once and the Hub, Relationships, Register, Rate Sheet and the other apps all recognize you.',
          where: 'Opening any page while signed out sends you to the sign-in page, then back to where you were.',
          link: { href: HUB, label: 'Open the Hub' },
          why: 'Controls who can use each tool, and stamps your name on quotes, notes and saved work.',
          steps: ['Open the Hub or any tool.', 'Sign in with your CodeBlue Microsoft account if asked.', 'Use Sign Out (top right of Relationships, Register and Rate Sheet) when finished.'],
          notes: ['Your name appears as the Requestor on Send to Inside Sales emails.', 'Some tools (Commissions, Collections) are limited to specific people even after you sign in.'],
          added: '2026-09-15', updated: '2026-10-07', kw: ['login', 'microsoft', 'password', 'sso'] },
        { id: 'home-screen', title: 'Home screen and tiles',
          def: 'The first screen of the Hub ("What can we build for you today?"). Each numbered tile launches a tool.',
          where: 'Hub home. Click the CodeBlue logo in the header from anywhere to return here.',
          link: { href: HUB, label: 'Open the Hub home screen' },
          why: 'One launch point for every tool: Solutions Creator, Relationships, Register, Customer Rate Sheet Sign Up, Commissions and Collections.',
          steps: ['Click a tile.', 'Solutions Creator opens inside the Hub; the others open their own apps.'],
          notes: ['The Solutions Creator tile shows an "N selected" badge when you have items in a solution.', 'Commissions and Collections tiles only appear for people with access.', 'The Help Center button in the header opens this guide.'],
          added: '2026-09-16', updated: '2026-10-07', kw: ['tiles', 'launcher', 'menu', 'start'] },
        { id: 'help-center', title: 'Help Center (this guide)',
          def: 'A searchable, always-current reference to what every CodeBlue tool can do, with links straight to each feature.',
          where: 'Hub header, the Help Center button (open book), next to Clyde Support. It also lives at /help/.',
          link: { href: 'index.html', label: 'Open the Help Center' },
          why: 'Learn what a feature is for, where to find it and how to use it, without asking a teammate.',
          steps: ['Type in the search box (press / to jump to it), or browse the index on the left.', 'Open an article and use its Open button to jump straight to that feature.', 'See What\'s New for a dated list of recent changes.'],
          notes: ['The Services section is built automatically from the Hub\'s service catalog, so new services appear on their own.', 'Spot something missing or out of date? Use Clyde Support in the Hub header.'],
          added: '2026-10-07', updated: '2026-10-07', kw: ['documentation', 'manual', 'faq', 'guide', 'reference'] },
        { id: 'help-suggestions', title: 'Clyde Support (send feedback)',
          def: 'A form in the Hub header for suggesting a feature, reporting an issue or error, or asking for help.',
          where: 'Hub header, the Clyde Support button (question-mark icon). Formerly called Help / Suggestions.',
          link: { href: HUB, label: 'Open the Hub' },
          why: 'Gets your message, with the screen you were on and your browser details, straight to Michael Bergamo.',
          steps: ['Click Clyde Support.', 'Pick a type: suggestion, report an issue / error, ask for help, or other.', 'Describe it in Your Message. Optionally paste or attach up to 5 screenshots.', 'Add a Reply-To email if you want an answer, then Send.'],
          notes: ['Anyone signed in can use it.', 'Large screenshots are shrunk automatically; if they are still too big you will be asked to attach fewer or smaller ones.'],
          added: '2026-10-05', updated: '2026-10-05', kw: ['help / suggestions', 'feedback', 'bug', 'report', 'support', 'screenshot'] },
        { id: 'theme-toggle', title: 'Light and dark theme',
          def: 'A round moon/sun button in the Hub header that switches between dark and light themes.',
          where: 'Hub header, far right, next to Help Center and Clyde Support.',
          link: { href: HUB, label: 'Open the Hub' },
          why: 'Pick whichever is easier to read on your screen or in a customer meeting.',
          steps: ['Click the button. Your choice is remembered in this browser.'],
          notes: ['With no saved choice, the Hub follows your device\'s light or dark setting.'],
          added: '2026-09-25', updated: '2026-09-25', kw: ['dark mode', 'light mode', 'appearance'] }
      ]
    },
    {
      id: 'solutions-hub', title: 'Solutions Hub',
      intro: 'Building a solution with a customer: find services, configure options, review the quote, send it, and save it to the customer. For what each service is, see the Services section.',
      articles: [
        { id: 'solutions-creator', title: 'Solutions Creator',
          def: 'The main workspace in the Hub. A search box and tiles for each service pillar let you drill from pillar to service to category and build a solution.',
          where: 'Hub home, tile 01 Solutions Creator ("Start building").',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'The place to walk a customer through what CodeBlue can provide and capture what they choose.',
          steps: ['Open Solutions Creator.', 'Search, or tap a pillar tile.', 'Tap a service, then a category if the service has them.', 'Choose options and tap Add to Solution.'],
          notes: ['The breadcrumb in the header reads Solutions Creator / Pillar / Service / Category. The back arrow goes up one level.', 'Each tile shows an "N selected" badge.', 'Nothing here commits the customer to anything; it is a conversation tool.'],
          added: '2026-09-16', updated: '2026-10-05', kw: ['build', 'quote', 'pillars', 'browse', 'start'] },
        { id: 'search-services', title: 'Search services (typed and voice)',
          def: 'A search box at the top of Solutions Creator that finds services and categories by name.',
          where: 'Solutions Creator, the box labelled "Search services".',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Jump straight to what the customer is asking about, such as "help desk" or "cameras", without clicking through pillars.',
          steps: ['Type a word. Up to 8 matches appear with their path.', 'Click a result to go straight there.', 'Click the microphone to search by voice.', 'Click the x to clear.'],
          notes: ['The microphone only appears in browsers that support speech recognition, such as Chrome and Edge.'],
          added: '2026-09-16', updated: '2026-09-16', kw: ['find', 'voice', 'microphone', 'lookup'] },
        { id: 'selecting-options', title: 'Selecting options, quantities and Add to Solution',
          def: 'Services and categories offer options as buttons or chips, quantities with minus/plus buttons, and sometimes Monthly / One-Time toggles. The Add button commits your choices to the solution.',
          where: 'Any service or category screen, the Add to Solution button at the bottom.',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Turns what the customer wants into line items on the quote.',
          steps: ['Pick options or set quantities with the - and + buttons.', 'Check the Monthly Total and Onboarding Total shown on the screen.', 'Tap Add to Solution. The Solution badge count in the header goes up.'],
          notes: ['Tapping the same option again removes it.', 'The device-count control on Cyber Security categories adjusts several related products together; fine-tune any product afterward.'],
          added: '2026-09-16', updated: '2026-09-16', kw: ['quantity', 'add', 'toggle', 'monthly', 'onboarding'] },
        { id: 'parts-and-computer-builder', title: 'Parts lists and the Computer Configuration builder',
          def: 'Equipment categories list products with SKUs, specs and quantities. Computers and servers use a builder where you pick form factor, CPU, memory, storage, brand, warranty and add-ons.',
          where: 'Equipment-type categories, for example IT Services > Equipment Sales > Computers or Servers.',
          link: { href: HUB + '?pillar=it&service=equipment-sales&category=es-computers', label: 'Open Equipment Sales > Computers' },
          why: 'Configures new equipment to spec, with a live preview you can show the customer.',
          steps: ['Choose a Form Factor first; the other rows appear after that.', 'Pick CPU, RAM, Storage, Brand and Warranty. Unpicked choices narrow as you go.', 'Watch the Configuration Preview card.', 'Tap Add to Solution.'],
          notes: ['Tap an option heading to preview its photo.', 'Some rows show a Recommended note when another item\'s quantity triggers it, and some ranges auto-fill from another category (for example speaker count to amplifier size).', 'The Configuration Preview carries onto the Solution Summary and printed quote, but not the emailed quote.'],
          added: '2026-09-22', updated: '2026-09-22', kw: ['computer', 'server', 'bom', 'parts', 'sku', 'laptop', 'desktop', 'config'] },
        { id: 'scope-of-work', title: 'Scope of Work (labor) lines',
          def: 'Optional labor lines on a category, billed at CodeBlue\'s hourly rate, each with hours, price, quantity and a full scope description.',
          where: 'Category screens, under the heading Scope of Work (Optional).',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Prices the installation or configuration work that goes with the products, and shows the customer exactly what is included.',
          steps: ['Set a quantity on a labor line.', 'Tap the line to read the scope bullets and Dependencies for Success.', 'Tap Add to Solution.'],
          notes: ['The hourly rate is set once on the Solution Summary and applies to all scope pricing.', 'Camera install labor follows the Camera Placement Photos count automatically.'],
          added: '2026-09-16', updated: '2026-10-07', kw: ['labor', 'hours', 'install', 'sow', 'dependencies'] },
        { id: 'rep-notes', title: 'Rep Notes and voice dictation',
          def: 'A free-text box on category and service screens for configuration details, site conditions and customer requests, with a microphone for dictation.',
          where: 'Bottom of category and service screens: Rep Notes (optional).',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Passes what you heard in the meeting to the inside rep fulfilling the quote.',
          steps: ['Type, or tap the microphone to dictate.', 'Tap Add to Solution.'],
          notes: ['Notes appear on the Summary and in the Inside Sales and PeopleFirst output.', 'Dictation only works in browsers that support speech recognition.'],
          added: '2026-09-16', updated: '2026-09-16', kw: ['notes', 'dictate', 'voice', 'comments'] },
        { id: 'project-mode', title: 'Project Mode (gold stars and Project tray)',
          def: 'A mode that adds gold stars to tiles. Starring an area drops a placeholder into a Project tray, a checklist of areas you still need to configure.',
          where: 'Solutions Creator, the Project Mode button near the top right of the title.',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Plan a multi-part project and make sure nothing is forgotten before you finish the quote.',
          steps: ['Click Project Mode.', 'Tap the star on each area you want in the project.', 'Open the tray at the bottom to see items grouped by pillar; tap one to jump into it or x to remove it.', 'Review Project opens the Solution Summary.'],
          notes: ['Starring does not add anything priced; it is only a reminder.', 'Starred and configured areas glow gold.'],
          added: '2026-09-23', updated: '2026-09-23', kw: ['stars', 'tray', 'checklist', 'project'] },
        { id: 'solution-summary', title: 'Solution Summary',
          def: 'The running quote for the conversation: every selected item grouped by pillar, with options, rep notes, configurations and scope of work, plus the customer quote block and Outcomes.',
          where: 'Hub header, the Solution button (shows an item count), or Review Project.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Review everything with the customer, adjust the hourly rate, then print, email, send to inside sales or save.',
          steps: ['Click Solution in the header.', 'Review items and Remove any you do not want.', 'Adjust CodeBlue\'s Hourly Rate with - and +.', 'Print, email, send or save (see the related articles).', 'Close returns you to where you were.'],
          notes: ['If nothing is selected it says "Nothing selected yet".', 'The Summary doubles as the print layout.'],
          added: '2026-09-15', updated: '2026-10-07', kw: ['quote', 'bill of materials', 'bom', 'review', 'total'] },
        { id: 'project-overview', title: 'Project Overview and Still to Configure',
          def: 'A diagram at the top of the Summary that groups the solution by service area, with a list of starred items you have not configured yet.',
          where: 'Top of the Solution Summary, when you used Project Mode.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Shows the shape of the whole project and what is still missing.',
          steps: ['Use Project Mode stars.', 'Open Solution.', 'Tap an unfinished item to jump back into it.'],
          notes: ['It shows on screen and in Print Quote, but deliberately not in the emailed quote or the Inside Sales email, because email programs often strip embedded images.'],
          added: '2026-09-23', updated: '2026-09-23', kw: ['diagram', 'unfinished', 'remaining'] },
        { id: 'print-quote', title: 'Print Quote',
          def: 'Opens your browser\'s print dialog for the Summary page: logo, bill of materials, scope and outcomes.',
          where: 'Solution Summary, the Print Quote button.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Hand the customer a paper copy or save the quote as a PDF.',
          steps: ['Open Solution.', 'Click Print Quote.', 'Print, or choose Save as PDF.'],
          notes: ['Includes the Computer Configuration visual and Project Overview graphic.', 'The PeopleFirst proposal has its own print layout.'],
          added: '2026-09-15', updated: '2026-09-23', kw: ['pdf', 'paper'] },
        { id: 'email-quote', title: 'Email Quote to Customer',
          def: 'Emails a branded HTML quote to the address you type, sent from CodeBlue\'s mail account.',
          where: 'Solution Summary, the Customer email field and the Email Quote to Customer button.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Gets the quote to the customer right away, with brand called out first and scope-of-work labor included.',
          steps: ['Enter a valid customer email.', 'Click the button; it reads Sending... then Sent.', 'If it fails, an error appears under the buttons.'],
          notes: ['A valid email is required.', 'Company and contact names appear in the quote header if filled in.'],
          added: '2026-09-15', updated: '2026-10-07', kw: ['send', 'customer', 'quote', 'email'] },
        { id: 'send-to-inside-sales', title: 'Send to Inside Sales',
          def: 'Emails the full solution to Quotes@codebluetechnology.com so inside sales can build the real quote in ConnectWise.',
          where: 'Solution Summary, the Send to Inside Sales button (opens a window).',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Hands your scoped solution to the team that matches CodeBlue SKUs and finishes pricing.',
          steps: ['Click Send to Inside Sales.', 'Enter the Company Name and the Contact Name the quote is addressed to.', 'Click Send.'],
          notes: ['Both names are required.', 'The email names you as the Requestor and includes rep notes.', 'Camera layout photos arrive as a grid of pictures, four across, with the camera counts under each. They are shrunk to keep the email near 2 MB.', 'Unit and extended prices are blank for most hardware because it is not priced yet.'],
          added: '2026-09-15', updated: '2026-10-07', kw: ['quotes@', 'inside sales', 'requestor', 'connectwise', 'photos'] },
        { id: 'outcomes', title: 'Outcomes: Risk Reduced, Uptime Gained, Cost Avoided',
          def: 'Three cards on the Summary that describe what the selected services mean for the business, as impact rather than price.',
          where: 'Solution Summary, the Outcomes section.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Talking points that connect each service to risk, uptime and cost.',
          steps: ['Build the solution.', 'Scroll to Outcomes.'],
          notes: ['A card appears only if a selected service carries that outcome. The wording comes from tags on each service; it is not price math.'],
          added: '2026-09-15', updated: '2026-09-15', kw: ['risk', 'uptime', 'cost', 'talking points'] },
        { id: 'cross-sell-hints', title: 'Cross-sell gold glow and Summary reminders',
          def: 'A gold glow marks a recurring product that is still missing, and gold banners on the Summary remind you with a Go to button.',
          where: 'Equipment Sales (Computers, Servers), IT Services > Cyber Security, and the Solution Summary.',
          link: { href: HUB + '?pillar=it&service=cyber-security', label: 'Open Cyber Security' },
          why: 'Makes sure recurring protection is sold alongside new hardware.',
          steps: ['Pick an EDR Anti-Virus or Patch Management add-on on a computer or server.', 'Follow the glow from IT Services to Cyber Security to the matching product row.', 'Add the recommended product; the banner disappears.'],
          notes: ['Selling Guardz also requires one SentinelOne license, and the SentinelOne row glows with that note.', 'A banner only shows if the triggering product is actually in the solution.'],
          added: '2026-09-16', updated: '2026-09-23', kw: ['upsell', 'recommend', 'edr', 'patch', 'guardz', 'sentinelone'] },
        { id: 'managed-it-peoplefirst', title: 'Managed IT: PeopleFirst membership and A La Carte',
          def: 'How Managed IT is sold: PeopleFirst Membership (every full-time staff member enrolled, one price per member per month) or A La Carte (each device and service priced individually).',
          where: 'IT Services > Managed IT Services, under How is this sold?',
          link: { href: HUB + '?pillar=it&service=managed-it', label: 'Open Managed IT Services' },
          why: 'Sizes the network, selects firewall, security software and add-ons, and shows the monthly and onboarding numbers.',
          steps: ['Pick the approach.', 'Set Full-Time Staff Members and device counts under Size the network.', 'Choose a firewall, security software and add-ons.', 'Set the Support Labor Rate.', 'Review The Numbers and Add to Solution.'],
          notes: ['A side panel of pills lights up as coverage is added (computer, server and networking support, quarterly risk evaluation).', 'Travel is a per-deal choice, Travel Included or One-Way Trip Charge Applies, and it carries through to Check Out.', 'An existing-customer onboarding discount can apply for companies already with CodeBlue.'],
          added: '2026-09-15', updated: '2026-09-23', kw: ['peoplefirst', 'members', 'managed', 'firewall', 'support', 'onboarding'] },
        { id: 'current-it-spend', title: 'Customer\'s current IT spend and invoice comparison',
          def: 'Optional fields on the Managed IT screen for what the customer pays today, used for an old-versus-new comparison on the PeopleFirst proposal.',
          where: 'Managed IT screen: Customer\'s Current Monthly IT Spend and Or Upload Their Current Invoice (PDF).',
          link: { href: HUB + '?pillar=it&service=managed-it', label: 'Open Managed IT Services' },
          why: 'Shows the customer their monthly savings or increase.',
          steps: ['Enter the customer\'s current monthly spend.', 'Optionally choose a PDF invoice. Remove or upload a different one if needed.'],
          notes: ['Invoice reading by AI is not available in this version. If you see that message, type the monthly total by hand; the comparison works from that number.', 'Leave it blank to skip the comparison.'],
          added: '2026-09-23', updated: '2026-09-23', kw: ['invoice', 'savings', 'comparison', 'upload'] },
        { id: 'peoplefirst-proposal', title: 'Check Out: PeopleFirst Proposal',
          def: 'A print-ready proposal built live from the solution, for the second meeting.',
          where: 'Solution Summary, the Check Out - PeopleFirst Proposal button. It only shows when PeopleFirst is chosen and the member count is above zero.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Gives the customer a formal, signable proposal.',
          steps: ['Pick PeopleFirst and set members.', 'On the Summary, click the Check Out button.', 'Fill in Company Name and Site Address.', 'Print the page.'],
          notes: ['Sections include personalized support, coverage in detail, devices covered, how to engage, investment summary, old versus new monthly investment and acceptance signature lines.', 'Monthly Savings or Monthly Increase appears if a current spend was entered.'],
          added: '2026-09-15', updated: '2026-09-23', kw: ['proposal', 'checkout', 'signature', 'print', 'peoplefirst'] },
        { id: 'vcio', title: 'Fractional CIO (vCIO) time',
          def: 'A slider for hours per month of strategic IT leadership, from 2 to 8, priced at the hourly rate.',
          where: 'IT Services, the vCIO service.',
          link: { href: HUB + '?pillar=it', label: 'Open IT Services' },
          why: 'Quotes ongoing CIO-level guidance sized to the customer.',
          steps: ['Set Hours per month with - and +.', 'Check the Monthly Investment.', 'Add to Solution.'],
          notes: ['The sliding scale is the rep\'s call based on the customer\'s needs.'],
          added: '2026-09-16', updated: '2026-09-16', kw: ['cio', 'virtual', 'strategy', 'hours'] },
        { id: 'camera-photo-plan', title: 'Camera Placement Photos',
          def: 'Upload photos of the spaces to cover, then drag Bullet, Dome or Turret cameras onto each photo. Quantities and install labor update from the placements.',
          where: 'Premise Security > IP Security Camera Systems > Cameras, in the block under the product list.',
          link: { href: HUB + '?pillar=security&service=ip-cameras&category=cam-cameras', label: 'Open IP Security Camera Systems > Cameras' },
          why: 'Counts cameras visually with the customer and gives installers and inside sales a marked-up picture.',
          steps: ['Tap + Add photo (on a phone or tablet you can use the camera).', 'Drag a camera type from Drag onto a photo onto the image; choose White or Black.', 'Select a marker to remove it, or Remove photo to drop a photo.', 'Rename photos (for example "Front entrance"); the name shows under the photo in the email.', 'Tap Add to Solution to record everything as one camera job.'],
          notes: ['Photos stay in your browser session unless you save the solution to a customer.', 'When saved, the marked-up photos (with numbered cameras) are attached to the customer\'s ConnectWise company, and only changed photos are attached again on update.', 'If you hand-edit the install scope quantity, the camera plan stops overwriting it.'],
          added: '2026-10-07', updated: '2026-10-07', kw: ['cameras', 'photos', 'bullet', 'dome', 'turret', 'drag', 'placement', 'security'] },
        { id: 'save-to-customer', title: 'Save a solution to a customer',
          def: 'Saves the working solution, with documents and images, to a customer\'s dashboard so it can be reopened and edited later.',
          where: 'Solution Summary, the Save to customer button; after saving, Update saved solution and Save as new.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Keeps each customer\'s solutions in one place, visible to the team on the Relationships dashboard.',
          steps: ['Add something to the solution (the button is off until you do).', 'Click Save to customer.', 'Pick the customer, name the solution (a name is suggested) and attach any files, up to 100 MB each.', 'Save.', 'To change it later, open it from the customer\'s Solutions card, edit, then Update saved solution or Save as new.'],
          notes: ['A banner shows Editing saved solution while one is reopened.', 'Starting from a customer\'s dashboard (+ New solution) pre-selects that customer.', 'Camera photos are saved automatically and attached in ConnectWise; if the customer has no ConnectWise company you will be told they were not attached.', 'Needs your Relationships access; customers outside your territory are not available.'],
          added: '2026-10-07', updated: '2026-10-07', kw: ['save', 'reopen', 'edit', 'customer', 'dashboard', 'update', 'attachments'] },
        { id: 'link-connectwise-project', title: 'Link a solution to a ConnectWise project',
          def: 'Gives each saved solution a unique link, and posts that link as a Comment on a Pre-Sales project in ConnectWise.',
          where: 'Solution Summary, after a solution is saved or reopened: Copy link and Link to ConnectWise project.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Creates a direct ConnectWise reference to the solution you are building.',
          steps: ['Save the solution.', 'Click Link to ConnectWise project.', 'Filter by project or company and pick the project.', 'A message confirms the note was posted.'],
          notes: ['Copy link copies the unique link so you can paste it into ConnectWise yourself.', 'The summary banner lists linked projects and flags a failed note.', 'A project already linked is not offered again; the customer\'s own projects are listed first.'],
          added: '2026-10-07', updated: '2026-10-07', kw: ['link', 'project', 'presales', 'pre-sales', 'comment', 'url'] },
        { id: 'start-over', title: 'Start Over',
          def: 'Clears the items from the current solution.',
          where: 'Bottom of the Solution Summary, Start Over.',
          link: { href: HUB + '?go=summary', label: 'Open the Solution Summary' },
          why: 'Begin a new conversation without leftovers from the last one.',
          steps: ['Open Solution.', 'Click Start Over at the bottom.'],
          notes: ['There is no confirmation prompt.', 'A solution you already saved to a customer is untouched.'],
          added: '2026-09-15', updated: '2026-09-15', kw: ['reset', 'clear', 'new'] },
        { id: 'call-experience', title: 'Zultys Call Experience Configurator',
          def: 'An 18-section questionnaire for Zultys phone deployments that you work through with the customer on-site.',
          where: 'Solutions Creator, the Zultys Call Experience tile (Open Configurator).',
          link: { href: '../call-experience.html', label: 'Open the Call Experience Configurator' },
          why: 'Captures how the customer\'s calls should work, as a reference for the Project Engineer.',
          steps: ['Answer top to bottom; Yes/No answers unlock follow-ups and sections unlock as you go.', 'Watch the progress pill.', 'At the end fill in company, site and prepared-by.', 'Use Email This Configuration, Copy as HTML or Print.'],
          notes: ['Sections include phone count, extensions, voicemail, incoming calls, call monitoring and recording, paging, fax, remote workers, DIDs, outbound restrictions and after-hours handling.', 'Call monitoring and recording are flagged as requiring ZAC.', 'The result is a working design subject to final review by the Project Engineer.'],
          added: '2026-09-16', updated: '2026-09-16', kw: ['zultys', 'phone', 'voip', 'questionnaire', 'call flow', 'pbx'] },
        { id: 'image-preview', title: 'Image preview',
          def: 'Click a product or option photo to see it enlarged with a caption.',
          where: 'Anywhere a photo appears on a product or option, such as the computer builder and firewall choices.',
          link: { href: HUB + '?go=creator', label: 'Open Solutions Creator' },
          why: 'Show the customer exactly what a product looks like.',
          steps: ['Click the picture.', 'Close with the x or by clicking the dim background.'],
          notes: [], added: '2026-09-22', updated: '2026-09-22', kw: ['photo', 'picture', 'lightbox', 'zoom'] }
      ]
    }
  );
})();
